site_name: nanri
pages:
    - Home: index.md
    - About: about.md
    - locvps: 'locvps.md'
    - shell: 
        - 'shell': 'shell/shell.md'
        - 'shortcut': 'shell/shortcut.md'        
    - jh:
        - 'jh': 'jh/jh.md'
    - bpm:
        - 'bpm': 'bpm/bpm.md'
    - 201706: 201706.md
    - elk: elk.md
    - es: es.md
    - vagrant: vagrant.md
    - docker: docker.md
    - kafka: kafka.md
    - jeecg: jeecg.md
    - 设备:
        - 'equipment': 'equipment/equipment.md'
        - 'equipmentinstall': 'equipment/equipmentinstall.md'
    - HDP: HDP.md
