site_name: nanri
pages:
    - Home: index.md
    - About: about.md
    - locvps: 'locvps.md'
    - shell: 
        - 'shell': 'shell/shell.md'
    - jh:
        - 'jh': 'jh/jh.md'
    - 201706: 201706.md
    - elk: elk.md
    - es: es.md
    - vagrant: vagrant.md
    - docker: docker.md
    - kafka: kafka.md
    - equipment: equipment.md
    - shortcut: shortcut.md
    - HDP: HDP.md
    - equipmentinstall: equipmentinstall.md

