site_name: nanri
pages:
    - Home: index.md
    - About: about.md
    - 201706: 201706.md
    - elk: elk.md
    - es: es.md
    - vagrant: vagrant.md
    - docker: docker.md
    - equipment: equipment.md
    - shortcut: shortcut.md
    - equipmentinstall: equipmentinstall.md

